### ISSUE TITLE
ошибки в глобальных стилях

### ISSUE THREAD

**Issue by AlexR0v** [Atlantis-Academy/react-learn-landing#2]
при попытке коммита мне выдает вот такую ошибку - 20:1 error Expected an assignment or function call and instead saw an expression @typescript-eslint/no-unused-expressions.
там у меня находится вот это - 
injectGlobal`
  * {
    box-sizing: border-box;
  }
.........

я проверил документацию emotion, но у меня все сделано именно как там указано, вот ссылка на их доку https://emotion.sh/docs/emotion#global-styles

так как это можно исправить?

а он у меня точно правильно работает? выдает вот такую простыню и это сейчас,там только 1 ошибка, до этого ошибок было 24 и простыня была в 24 раза больше - это крайне неудобно.

0 file committed, 29 files failed to commit: build(header) add header style husky > pre-commit (node v12.18.1) Stashing changes... [started] Stashing changes... [skipped] → No partially staged files found... Running tasks... [started] Running tasks for *.{js,ts,tsx,yml,yaml,json,graphql,md} [started] Running tasks for *.{ts,tsx} [started] Running tasks for *.{js,jsx,ts,tsx} [started] prettier --write --config D:\web\react\react-learn-landing\node_modules\@monstrs\prettier-config\dist\index.js --ignore-path D:\web\react\react-learn-landing\node_modules\@monstrs\prettier-config\.prettierignore [started] bash -c "tsc --noEmit" [started] eslint --fix --config D:\web\react\react-learn-landing\node_modules\@monstrs\eslint-config\dist\index.js [started] prettier --write --config D:\web\react\react-learn-landing\node_modules\@monstrs\prettier-config\dist\index.js --ignore-path D:\web\react\react-learn-landing\node_modules\@monstrs\prettier-config\.prettierignore [completed] git add [started] git add [completed] Running tasks for *.{js,ts,tsx,yml,yaml,json,graphql,md} [completed] eslint --fix --config D:\web\react\react-learn-landing\node_modules\@monstrs\eslint-config\dist\index.js [failed] → Running tasks for *.{js,jsx,ts,tsx} [failed] → bash -c "tsc --noEmit" [completed] Running tasks for *.{ts,tsx} [completed] Running tasks... [failed] × eslint --fix --config D:\web\react\react-learn-landing ode_modules\@monstrs\eslint-config\dist\index.js found some errors. Please fix them and try committing again. D:\web\react\react-learn-landing\site\ui\theme\index.tsx 20:1 error Expected an assignment or function call and instead saw an expression @typescript-eslint/no-unused-expressions ✖ 1 problem (1 error, 0 warnings) husky > pre-commit hook failed (add --no-verify to bypass)

**Comment by TorinAsakura** [comment]
@TorinAsakura https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-expressions.md

**Comment by AlexR0v** [comment]
Правильно понимаю, что для начала мне нужно установить eslint-plugin и добавить .eslinrc?

никогда с этим не имел дела, поэтому и не понимаю - куда мне нужно добавить данное правило.

**Comment by TorinAsakura** [comment]
> Правильно понимаю, что для начала мне нужно установить eslint-plugin и добавить .eslinrc?
> 
> никогда с этим не имел дела, поэтому и не понимаю - куда мне нужно добавить данное правило.

ничего добавлять не надо, нужно исправить ошибку

**Comment by TorinAsakura** [comment]
и рекомендую запускать своё приложение в докере

**Comment by AlexR0v** [comment]
> > Правильно понимаю, что для начала мне нужно установить eslint-plugin и добавить .eslinrc?
> > никогда с этим не имел дела, поэтому и не понимаю - куда мне нужно добавить данное правило.
> 
> ничего добавлять не надо, нужно исправить ошибку

так я поэтому и написал ишью, т.к. не понимаю в чем ошибка - я сделал все как указано в документации к эмоушен.

**Comment by TorinAsakura** [comment]
> > > Правильно понимаю, что для начала мне нужно установить eslint-plugin и добавить .eslinrc?
> > > никогда с этим не имел дела, поэтому и не понимаю - куда мне нужно добавить данное правило.
> > 
> > 
> > ничего добавлять не надо, нужно исправить ошибку
> 
> так я поэтому и написал ишью, т.к. не понимаю в чем ошибка - я сделал все как указано в документации к эмоушен.

ну так разберись, ошибка тебе известна, тебе только нужно понять откуда ноги растут

**Comment by TorinAsakura** [comment]
Тем более я твой код не видел

**Comment by AlexR0v** [comment]
> и рекомендую запускать своё приложение в докере

ок, буду разбираться, раз мне известна ошибка. А по этому можно подробнее - что это? да, я знаю что ты сейчас обо мне думаешь, но я не понимаю.

**Comment by TorinAsakura** [comment]
> > и рекомендую запускать своё приложение в докере
> 
> ок, буду разбираться, раз мне известна ошибка. А по этому можно подробнее - что это? да, я знаю что ты сейчас обо мне думаешь, но я не понимаю.

https://bit.ly/30JmMlf - в первый и последний раз

**Comment by AlexR0v** [comment]
спасибо, рассмешил)))
