### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by AlexR0v** [Atlantis-Academy/react-learn-landing#3]
не могу запустить проект.

вот мой dockerfile:

FROM node:12.18.1
WORKDIR /app
COPY package.json yarn.lock /app/
RUN yarn install
COPY . /app
EXPOSE 3000
CMD ["yarn", "start"]

создаю образ - docker build -t react-learn-landing:1.0
образ создается без ошибок
монтирую образ в контейнер - docker run -it -v ${PWD}:/app -v /app/node_modules -p 3000:3001 -e CHOKIDAR_USEPOLLING=true alexr0v/react-learn-landing:1.0

в консоли все проходит хорошо, видно как запустились все команды, пытаюсь открыть адрес http://localhost:3000/  в ответ получаю - Сайт localhost не отправил данных.

проделываю все тоже самое с create-react-app - все запускается без проблем.
создавал обычный образ с обычной html страницей - все работает.

Делаю вывод что мой webpackDevserver настроен как-то не верно, но не пойму что именно. 
Гуглил, везде только ответы по create-react-app, искал в документации, там нет ни слова по react, обычный образ у меня монтируется и открывается как и указано в документации.

Просьба подсказать - куда хотя бы копать? мое предположение с devserver верно?

**Comment by TorinAsakura** [comment]
Снова телепатия?

**Comment by AlexR0v** [comment]
> Снова телепатия?

В смысле? Не понял.

**Comment by TorinAsakura** [comment]
Я вот тоже ничего не понял

**Comment by AlexR0v** [comment]
Так а что показать? Dockerfile показал. Использую его одинаково у себя и при create-react-app, только у меня образ монтируется но не открывается, а при create-react-app все работает отлично

**Comment by TorinAsakura** [comment]
Ну, мне подсказки исходя из чего строить?

**Comment by AlexR0v** [comment]
Раз в одном случае не работает, а в другом работает, значит что то с webpack моим. Так? Его показать? Могу сделать пр, чтобы разобрать этот случай. Кинуть пр?

**Comment by TorinAsakura** [comment]
> Раз в одном случае не работает, а в другом работает, значит что то с webpack моим. Так? Его показать? Могу сделать пр, чтобы разобрать этот случай. Кинуть пр?

А почему ты решил, что проблема именно с вебпаком?

**Comment by AlexR0v** [comment]
Ну при create-react-app работает же. Мне почему то кажется что именно с webpackом. Его девсервер у меня как то не так настроен.

**Comment by TorinAsakura** [comment]
> Ну при create-react-app работает же. Мне почему то кажется что именно с webpackом. Его девсервер у меня как то не так настроен.

Если ты думаешь, что у тебя девсервер "как то не так настроен", значит, я полагаю, его настроить должным образом прежде чем дёргать других. Да?

**Comment by AlexR0v** [comment]
Так в том то и дело, что пробовал по всякому. Прежде чем дергать, я уже пол интернета облазил, у меня вот толтко такая догадка сложилась. Если бы хоть ошибку какую выдавал, то было бы понятней, но все монтирование происходит отлично, в консоли вижу что вебпак запускается, девсервер работает, а адрес в браузере не открывается.

**Comment by AlexR0v** [comment]
И может я ошибаюсь, поэтому и спросил подсказку.

**Comment by TorinAsakura** [comment]
> И может я ошибаюсь, поэтому и спросил подсказку.

я не знаю
но, я бы на твоём месте проверил проверил работает ли девсервер локально и что происходит после запуска

**Comment by TorinAsakura** [comment]
@AlexR0v актуально?

**Comment by AlexR0v** [comment]
Я так и не разобрался почему у меня не работает.

**Comment by AlexR0v** [comment]
ничего не получается... точнее получается, но сайт не видно, образ монтируется, команды запускаются и все на этом.

есть где подсмотреть? я в бмв докерфайл глянул, офигел и закрыл от ужаса), мне че-нить попроще для начала.

**Comment by TorinAsakura** [comment]
> ничего не получается... точнее получается, но сайт не видно, образ монтируется, команды запускаются и все на этом.
> 
> есть где подсмотреть? я в бмв докерфайл глянул, офигел и закрыл от ужаса), мне че-нить попроще для начала.

так куда уж проще-то? Там докер образ элементарный в 15 строк, чего ты там закрыл от ужаса?

**Comment by AlexR0v** [comment]
95! там 95 строчек кода!) 
все туториалы, что я читал/смотрел ну максимум на 10 строк. И у тебя там нет самого Dockerfile, есть только docker-compoze, но даже в документации говориться, что докерфайл нужен. Значит можно без него, а как?
почему так много кода, куда смотреть? чем services yarn отличается от site, site-local и остальных? 
и другие подобные вопросы.

**Comment by TorinAsakura** [comment]
@AlexR0v Что за чушь ты несёшь?! Всё там есть, выполни рекурсивный поиск по проекту.

**Comment by AlexR0v** [comment]
да, извиняюсь, есть, думал что они должны лежать в корне проекта. Но вопросов стало еще больше...

**Comment by TorinAsakura** [comment]
@AlexR0v Вопросы - хорошо. Молчание - херь

**Comment by AlexR0v** [comment]
заработало! пойду напьюсь от счастья!)
