### ISSUE TITLE
Сделать адаптивную верстку готовых секций под планшет и мобильник

### ISSUE THREAD

**Issue by AlexR0v** [Atlantis-Academy/react-learn-landing#37]

**Comment by TorinAsakura** [comment]
@AlexR0v задачи должны иметь цикл жизни в котором они могут получить завершающий статус. В твоём случае это не задача, а задача-помойка.
Под каждую секцию которую ты адаптируешь создаётся задача.
В заголовке должна указываться суть, но не более.
В теле задачи описываешь детали и решения которые планируешь использовать при решении этой задачи.
