### ISSUE TITLE
Рубрика тупые вопросы.

### ISSUE THREAD

**Issue by AlexR0v** [Atlantis-Academy/react-learn-landing#41]
React-intl
не до конца понимаю как он работает и зачем нужен. Прочитал на выходных документацию, про форматы и даты - все понятно, конкретно как это используется у нас нет. Вот есть у нас он - для чего?

Docker
Зачем он нужен? я умею собрать образ, монтировать его в контейнер, но для чего? пелопатил тонну инфы (статьи, дока, видосики), но везде только одно - круто, образы, контейнеры, линукс, зависимости без изменений - и все, кроме этого так и не понял - зачем?

Тема проекта - этот вопрос прям срочный.
как в итоге к ней правильно обращаться? 
```fontSize='medium'``` - так лучше на вид, чем ```fontSize={theme.fontSizes.medium}```, а если размер меняется в зависимости от размеров экрана, то последний вариант будет выглядеть вообще вот так - 
```fontSize={[theme.fontSizes.small, theme.fontSizes.default, theme.fontSizes.medium]}```
При этом я понимаю, что ```fontSize='х'``` - никуда не годиться.

по поводу респосив стайл - как лучше делать разные размеры?
```<Layout flexBasis={[32, 44, 44]} />``` - в серенити
```<Layout flexBasis={['32px', '44px', '44px']} />``` - в бмв

в документации об этом сказано, что работает и так и так, договоритесь в команде как лучше.

**Comment by TorinAsakura** [comment]
**React-Intl**

Для определения стрингов, работы c ними, дальнейшей транслитерации (если потребуется). Без него ты всё описывал прямо в странице или компоненте, иначе говоря - хардкодил

**Docker**

Он нужен для запуска твоего проекта в изолированной, нейтральной от твоей системы, среде, в линуксе короче говоря.
Так для того, о чём ты читал и нужен, что за тупняк-то? Все пакеты и процессы на всех операционках исполняются по-разному в т.ч. typecheck, eslint, prettier, поэтому ПР который проходит проверки у тебя локально может не пройти через проверки на гитхабе.

**Тема**

theme.someThing.someThingProp использовать можно в компонентах, где ты один раз написал, завернул и забыл.
someThing='someThingProp' - нормальное обращение когда контекстом является исполняемая область, такая как, скажем, страница, или блок страницы
Сегодня закину тему в uikit, надеюсь успею

**Serenity** - проект - эталон, всё (почти), что в нём делается, по умолчанию является верным, пока не придумаю другое.

Постараюсь сегодня налить свежего фронта, опять же - если успею.

**Comment by AlexR0v** [comment]
"theme.someThing.someThingProp использовать можно в компонентах, где ты один раз написал, завернул и забыл." - но я же так и делал. someThing='someThingProp' - такое обращение у меня только в секциях больше нигде.

С нетерпением буду ждать больше фронта в серенити, это бы мне существенно помогло.

про Docker, просто почему-то ожидал большего от него, ну там чего-то глобального, масштабного, столько статей про него, столько восхищений, то что процессы на операционках исполняются по разному знал, но что-то не подумал.

**Comment by TorinAsakura** [comment]
@AlexR0v так блин, докер это не прикладное ПО для "Виндуза", это кусочек системы виртуализации, этот самый докер имейдж потом отгружается на сервера, там разворачивается, запускается, обслуживается, большинство современных нормальных сервисов сейчас так и работают

**Comment by AlexR0v** [comment]
@TorinAsakura  вот! я как раз про сервера, разворачивание и запускание! Везде в статьях говориться про то что это так круто и классно, но нигде нет инфы как это сделать, я понимаю, что это уже другая область, но хотелось бы понять КАК это делается. Насколько я понял, завернул все в образ и развернул на сервере, именно в том виде в котором завернул - так? если да, то мне этого достаточно.

**Comment by AlexR0v** [comment]
но не встречал я статьи, что бы вот так вот, на пальцах. В доке все запутанно.

**Comment by TorinAsakura** [comment]
@AlexR0v Нет. Не так. Но, что-то вроде того

**Comment by AlexR0v** [comment]
React-Intl - дальнейшей транслитерации (если потребуется) - если будут примеры, как это происходит, буду благодарен, в доке об этом написано, что нужно создавать json файлы с различными переводами и react-intl определят по ID  lang какой перевод использовать, мы же делам без json или без разницы какой формат?

**Comment by TorinAsakura** [comment]
> React-Intl - дальнейшей транслитерации (если потребуется) - если будут примеры, как это происходит, буду благодарен, в доке об этом написано, что нужно создавать json файлы с различными переводами и react-intl определят по ID lang какой перевод использовать, мы же делам без json или без разницы какой формат?

мы используем для этих целей lokalise
