### ISSUE TITLE
Автофилы в инпатах

### ISSUE THREAD

**Issue by AlexR0v** [Atlantis-Academy/react-learn-landing#44]
Как разобраться с этой информацией?

все разумное что я нашел указано в этой [статье](https://habr.com/ru/company/mailru/blog/301840/)
ну и собственно в [спецификации HTML](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill)

реализовал по примерам из спецификации, но как это проверить работает или нет?
@TorinAsakura как ты воспроизвел это? ты мне присылал скрин, как ты это воспроизвел это?

Никогда с этим не сталкивался, и даже не слышал, буду благодарен любой информации.

**Comment by TorinAsakura** [comment]
@AlexR0v Найди в настройках браузера автозаполнение и действуй
