### ISSUE TITLE
В каком формате указывать цвета?

### ISSUE THREAD

**Issue by AlexR0v** [Atlantis-Academy/react-learn-landing#46]
обратил внимание что в серенити цвета указаны в rgb.
искал информацию о разнице, нашел что в rgb лучше передает цвет в некоторых браузерах. 
Нашел вот такую [статью](https://habr.com/ru/post/496768/), в ней автор говорит о HSL, довольно убедительно высказывает аргументы в ее пользу. Почитав в других источниках, понял, что по цветопередаче не отличается от RGB.

Можно использовать HSL? система гораздо нагляднее и интуитивно понятнее.

**Comment by TorinAsakura** [comment]
Ради кода
