### ISSUE TITLE
Ошибка при создании коммита

### ISSUE THREAD

**Issue by AlexR0v** [Atlantis-Academy/react-learn-landing#48]
```
× prettier --write --config D:\web\react\react-learn-landing
ode_modules\@monstrs\prettier-config\dist\index.js --ignore-path D:\web\react\react-learn-landing
ode_modules\@monstrs\prettier-config\.prettierignore found some errors. Please fix them and try committing again.

���誮� ������� ��������� ��ப�.

husky > pre-commit hook failed (add --no-verify to bypass)
D:\web\react\react-learn-landing\node_modules\commitizen\dist\cli\strategies\git-cz.js:85
        throw error;
        ^

Error: git exited with error code 1
    at ChildProcess.<anonymous> (D:\web\react\react-learn-landing\node_modules\commitizen\dist\git\commit.js:807:28)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12) {
  code: 1,
  signal: null
}
error Command failed with exit code 1.
```

нашел [инфу](https://github.com/typicode/husky/issues/333), советуют сделать следующее - 
```
rm -rf .git/hooks/
rm -rf node_modules
yarn
```

мне это не помогло

либо [советуют](https://github.com/typicode/husky/issues/716) обойти husky, как и указано - ```add --no-verify to bypass```

С чем может быть связана эта ошибка? Пока не могу разобраться.

**Comment by TorinAsakura** [comment]
@AlexR0v ode_modules\@monstrs\prettier-config\.prettierignore found some errors. Please fix them and try committing again.
?

**Comment by AlexR0v** [comment]
Вот этот файл

```
.c9
.git
node_modules
coverage
dist
lib
.next
**/**/dist/*
**/**/lib/*
**/**/templates/*.yaml
**/templates/*.yaml
**/types/**
.terraform
```

**Comment by TorinAsakura** [comment]
Есть вероятность, что это реакция на кириллицу где-то. Но, тут сложно сказать без анализа. Для начала попробуй тоже самое в чистой репе

**Comment by TorinAsakura** [comment]
И запусти yarn format отдельно

**Comment by AlexR0v** [comment]
на чистом проекте все без проблем. В чем может быть проблема? кирилица в каком либо файле?

yarn format всегда запускаю. И yarn lint. Ошибка только при коммите.

**Comment by TorinAsakura** [comment]
> на чистом проекте все без проблем. В чем может быть проблема? кирилица в каком либо файле?
> 
> yarn format всегда запускаю. И yarn lint. Ошибка только при коммите.

нет нужды запускать их руками - это за тебя делает husjy

понятия не имею в чём
