### ISSUE TITLE
как вынести событие нажатия на ENTER в отдельную компоненту?

### ISSUE THREAD

**Issue by AlexR0v** [Atlantis-Academy/react-learn-landing#9]
со вчерашнего дня не могу разобраться, решил вынести в ишью. Все изменения в последнем ПР. Как передать отдельной функции обработчик формы? причем у меня их два, и это только пока.

**Comment by TorinAsakura** [comment]
Вероятно нужно написать экшен
Ну и можно ещё погуглить если уж совсем не понятно ничего https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_forms_through_JavaScript

**Comment by AlexR0v** [comment]
@ilyassab  привет. Андрей посоветовал обратиться к тебе. У меня возникла проблема. Моем ПР - https://github.com/Atlantis-Academy/react-learn-landing/pull/6, есть форма, на ней есть событие, которое по нажатию клавиши Enter запускает обработчик формы - 

  const handleKeyPress = event => {
    if (event.key === 'Enter') {
      handleForm()
    }
  }

Андрей, мне дал задание - "зачем ты этот код копипастишь? вынеси в утилиту и юзай"

и тут у меня возникла проблема, я не смог разобраться как это сделать, выше есть комментарий, в котором он говорит, что нужно сделать экшен. Но и тут я не смог разобраться. Андрей мне посоветовал подсмотреть код в бмв, но там на инпате я не нашел события по нажтию на клавишу.

Может быть я не там смотрю, но я совсем не могу разобраться. Прошу помощи.
